(define (problem pb8)
	(:domain blocksworld)
   	(:objects a b c d e f g h)
   	(:init (onTable a) 
   		(onTable b) 
   		(onTable c) 
   		(onTable d)
   		(onTable e) 
        (onTable f) 
        (onTable g) 
        (onTable h)
        (clear a)  
        (clear b) 
        (clear c) 
        (clear d) 
        (clear e) 
        (clear f)  
        (clear g) 
        (clear h)
	)
   	(:goal (and (on a b) 
   		(on b c) 
   		(on c d) 
   		(on d e) 
   		(on e f) 
   		(on f g)
        (on g h))
	)
)