(define (problem pb9)
   (:domain blocksworld)
   (:objects a b c d e f g h i)
   (:init (onTable a) (onTable b) (onTable c) (onTable d) (onTable e) 
          (onTable f) (onTable g) (onTable h) (onTable i) 
          (clear a)  (clear b) (clear c) (clear d) (clear e) 
          (clear f)  (clear g) (clear h) (clear i))
   (:goal (and (on a b) (on b c) (on c d) (on d e) (on e f) (on f g)
               (on g h) (on h i))))