; Generated by ProblemGenerator - Problem 1 at Wed Nov 23 18:40:51 BRST 2016
(define (problem pb1)
	(:domain drinkanddrive-generated)
	(:requirements :strips :typing :negative-preconditions)
	(:objects
		loc1 loc2 loc3 loc4 loc5 loc6 - location
		bar4 - bar
	)
	(:init
		(at loc1)

		(connected loc2 loc3)
		(connected loc3 loc2)
		(connected loc3 loc4)
		(connected loc4 loc3)
		(connected loc4 loc1)
		(connected loc1 loc4)
		(connected loc1 loc5)
		(connected loc5 loc1)
		(connected loc1 loc6)
		(connected loc6 loc1)
		(connected loc1 loc2)
		(connected loc2 loc1)
		(connected loc6 loc5)
		(connected loc5 loc6)

		(in bar4 loc4)

	)

	(:goal
		(and
			(at loc6)
		)
	)
)