; Generated by ProblemGenerator - Problem 1 at Tue Nov 22 16:23:53 BRST 2016
(define (problem pb1)
	(:domain drinkanddrive-generated)
	(:requirements :strips :typing :negative-preconditions)
	(:objects
		loc1 loc2 loc3 loc4 loc5 loc6 - location
		bar1 bar2 bar3 bar5 - bar
	)
	(:init
		(at loc1)

		(connected loc3 loc5)
		(connected loc5 loc3)
		(connected loc5 loc4)
		(connected loc4 loc5)
		(connected loc5 loc6)
		(connected loc6 loc5)
		(connected loc4 loc1)
		(connected loc1 loc4)
		(connected loc6 loc2)
		(connected loc2 loc6)
		(connected loc2 loc4)
		(connected loc4 loc2)
		(connected loc3 loc2)
		(connected loc2 loc3)
		(connected loc3 loc4)
		(connected loc4 loc3)
		(connected loc3 loc6)
		(connected loc6 loc3)
		(connected loc4 loc3)
		(connected loc3 loc4)

		(in bar1 loc1)
		(in bar2 loc2)
		(in bar3 loc3)
		(in bar5 loc5)

	)

	(:goal
		(and
			(at loc6)
		)
	)
)