; Generated by ProblemGenerator - Problem 2 at Wed Nov 23 18:40:52 BRST 2016
(define (problem pb2)
	(:domain drinkanddrive-generated)
	(:requirements :strips :typing :negative-preconditions)
	(:objects
		loc1 loc2 loc3 loc4 loc5 loc6 loc7 - location
		bar2 bar5 bar6 bar7 - bar
	)
	(:init
		(at loc1)

		(connected loc4 loc5)
		(connected loc5 loc4)
		(connected loc5 loc7)
		(connected loc7 loc5)
		(connected loc7 loc2)
		(connected loc2 loc7)
		(connected loc5 loc1)
		(connected loc1 loc5)
		(connected loc7 loc3)
		(connected loc3 loc7)
		(connected loc4 loc6)
		(connected loc6 loc4)
		(connected loc1 loc4)
		(connected loc4 loc1)
		(connected loc1 loc5)
		(connected loc5 loc1)
		(connected loc4 loc3)
		(connected loc3 loc4)
		(connected loc5 loc2)
		(connected loc2 loc5)
		(connected loc6 loc1)
		(connected loc1 loc6)
		(connected loc6 loc7)
		(connected loc7 loc6)
		(connected loc7 loc4)
		(connected loc4 loc7)
		(connected loc7 loc5)
		(connected loc5 loc7)

		(in bar2 loc2)
		(in bar5 loc5)
		(in bar6 loc6)
		(in bar7 loc7)

	)

	(:goal
		(and
			(at loc7)
		)
	)
)