; Generated by ProblemGenerator - Problem 3 at Tue Nov 22 16:23:54 BRST 2016
(define (problem pb3)
	(:domain drinkanddrive-generated)
	(:requirements :strips :typing :negative-preconditions)
	(:objects
		loc1 loc2 loc3 loc4 loc5 loc6 loc7 loc8 - location
		bar3 bar5 bar6 bar7 - bar
	)
	(:init
		(at loc1)

		(connected loc2 loc4)
		(connected loc4 loc2)
		(connected loc4 loc5)
		(connected loc5 loc4)
		(connected loc5 loc1)
		(connected loc1 loc5)
		(connected loc4 loc6)
		(connected loc6 loc4)
		(connected loc5 loc7)
		(connected loc7 loc5)
		(connected loc4 loc8)
		(connected loc8 loc4)
		(connected loc1 loc3)
		(connected loc3 loc1)
		(connected loc2 loc3)
		(connected loc3 loc2)
		(connected loc3 loc1)
		(connected loc1 loc3)
		(connected loc3 loc5)
		(connected loc5 loc3)
		(connected loc4 loc2)
		(connected loc2 loc4)
		(connected loc5 loc3)
		(connected loc3 loc5)
		(connected loc6 loc3)
		(connected loc3 loc6)
		(connected loc6 loc7)
		(connected loc7 loc6)
		(connected loc7 loc6)
		(connected loc6 loc7)

		(in bar3 loc3)
		(in bar5 loc5)
		(in bar6 loc6)
		(in bar7 loc7)

	)

	(:goal
		(and
			(at loc8)
		)
	)
)