; Generated by ProblemGenerator - Problem 4 at Tue Nov 22 16:23:54 BRST 2016
(define (problem pb4)
	(:domain drinkanddrive-generated)
	(:requirements :strips :typing :negative-preconditions)
	(:objects
		loc1 loc2 loc3 loc4 loc5 loc6 loc7 loc8 loc9 - location
		bar2 bar3 bar4 bar5 bar6 bar7 bar8 bar9 - bar
	)
	(:init
		(at loc1)

		(connected loc5 loc8)
		(connected loc8 loc5)
		(connected loc8 loc2)
		(connected loc2 loc8)
		(connected loc5 loc6)
		(connected loc6 loc5)
		(connected loc6 loc9)
		(connected loc9 loc6)
		(connected loc9 loc1)
		(connected loc1 loc9)
		(connected loc8 loc7)
		(connected loc7 loc8)
		(connected loc7 loc4)
		(connected loc4 loc7)
		(connected loc5 loc3)
		(connected loc3 loc5)
		(connected loc3 loc7)
		(connected loc7 loc3)
		(connected loc7 loc3)
		(connected loc3 loc7)
		(connected loc7 loc6)
		(connected loc6 loc7)
		(connected loc8 loc3)
		(connected loc3 loc8)

		(in bar2 loc2)
		(in bar3 loc3)
		(in bar4 loc4)
		(in bar5 loc5)
		(in bar6 loc6)
		(in bar7 loc7)
		(in bar8 loc8)
		(in bar9 loc9)

	)

	(:goal
		(and
			(at loc9)
		)
	)
)