; Generated by ProblemGenerator - Problem 5 at Wed Nov 23 18:40:52 BRST 2016
(define (problem pb5)
	(:domain drinkanddrive-generated)
	(:requirements :strips :typing :negative-preconditions)
	(:objects
		loc1 loc2 loc3 loc4 loc5 loc6 loc7 loc8 loc9 loc10 - location
		bar1 bar2 bar4 bar6 bar7 bar8 bar10 - bar
	)
	(:init
		(at loc1)

		(connected loc9 loc6)
		(connected loc6 loc9)
		(connected loc9 loc10)
		(connected loc10 loc9)
		(connected loc10 loc5)
		(connected loc5 loc10)
		(connected loc5 loc2)
		(connected loc2 loc5)
		(connected loc5 loc8)
		(connected loc8 loc5)
		(connected loc8 loc7)
		(connected loc7 loc8)
		(connected loc10 loc3)
		(connected loc3 loc10)
		(connected loc8 loc1)
		(connected loc1 loc8)
		(connected loc9 loc4)
		(connected loc4 loc9)
		(connected loc2 loc6)
		(connected loc6 loc2)
		(connected loc2 loc8)
		(connected loc8 loc2)
		(connected loc6 loc2)
		(connected loc2 loc6)
		(connected loc9 loc7)
		(connected loc7 loc9)

		(in bar1 loc1)
		(in bar2 loc2)
		(in bar4 loc4)
		(in bar6 loc6)
		(in bar7 loc7)
		(in bar8 loc8)
		(in bar10 loc10)

	)

	(:goal
		(and
			(at loc10)
		)
	)
)