; Generated by ProblemGenerator - Problem 1 at Sat Nov 26 18:02:20 BRST 2016
(define (problem pb1)
	(:domain drinkanddrive-constraints-generated)
	(:requirements :strips :typing :negative-preconditions)
	(:objects
		loc1 loc2 loc3 loc4 loc5 loc6 - location
		bar3 bar4 - bar
	)
	(:init
		(at loc1)

		(connected loc6 loc5)
		(connected loc5 loc6)
		(connected loc5 loc1)
		(connected loc1 loc5)
		(connected loc5 loc4)
		(connected loc4 loc5)
		(connected loc1 loc3)
		(connected loc3 loc1)
		(connected loc5 loc2)
		(connected loc2 loc5)
		(connected loc2 loc1)
		(connected loc1 loc2)
		(connected loc4 loc5)
		(connected loc5 loc4)
		(connected loc5 loc6)
		(connected loc6 loc5)

		(in bar3 loc3)
		(in bar4 loc4)

	)

	(:goal
		(and
			(at loc6)
		)
	)
	(:constraints
		(and
			(preference a1 (sometime (drunk)))
		)
	)
)