; Generated by ProblemGenerator - Problem 2 at Sat Nov 26 18:02:20 BRST 2016
(define (problem pb2)
	(:domain drinkanddrive-constraints-generated)
	(:requirements :strips :typing :negative-preconditions)
	(:objects
		loc1 loc2 loc3 loc4 loc5 loc6 loc7 - location
		bar2 bar4 bar5 - bar
	)
	(:init
		(at loc1)

		(connected loc7 loc6)
		(connected loc6 loc7)
		(connected loc6 loc4)
		(connected loc4 loc6)
		(connected loc4 loc1)
		(connected loc1 loc4)
		(connected loc1 loc5)
		(connected loc5 loc1)
		(connected loc6 loc2)
		(connected loc2 loc6)
		(connected loc2 loc3)
		(connected loc3 loc2)
		(connected loc1 loc3)
		(connected loc3 loc1)
		(connected loc2 loc1)
		(connected loc1 loc2)
		(connected loc3 loc1)
		(connected loc1 loc3)

		(in bar2 loc2)
		(in bar4 loc4)
		(in bar5 loc5)

	)

	(:goal
		(and
			(at loc7)
		)
	)
	(:constraints
		(and
			(preference a1 (sometime (drunk)))
		)
	)
)