; Generated by ProblemGenerator - Problem 3 at Sat Nov 26 18:02:20 BRST 2016
(define (problem pb3)
	(:domain drinkanddrive-constraints-generated)
	(:requirements :strips :typing :negative-preconditions)
	(:objects
		loc1 loc2 loc3 loc4 loc5 loc6 loc7 loc8 - location
		bar2 bar4 bar5 bar7 bar8 - bar
	)
	(:init
		(at loc1)

		(connected loc5 loc8)
		(connected loc8 loc5)
		(connected loc8 loc3)
		(connected loc3 loc8)
		(connected loc3 loc4)
		(connected loc4 loc3)
		(connected loc5 loc2)
		(connected loc2 loc5)
		(connected loc2 loc7)
		(connected loc7 loc2)
		(connected loc5 loc1)
		(connected loc1 loc5)
		(connected loc3 loc6)
		(connected loc6 loc3)
		(connected loc1 loc6)
		(connected loc6 loc1)
		(connected loc2 loc1)
		(connected loc1 loc2)
		(connected loc5 loc7)
		(connected loc7 loc5)
		(connected loc6 loc4)
		(connected loc4 loc6)
		(connected loc7 loc2)
		(connected loc2 loc7)

		(in bar2 loc2)
		(in bar4 loc4)
		(in bar5 loc5)
		(in bar7 loc7)
		(in bar8 loc8)

	)

	(:goal
		(and
			(at loc8)
		)
	)
	(:constraints
		(and
			(preference a1 (sometime (drunk)))
		)
	)
)