; Generated by ProblemGenerator - Problem 4 at Sat Nov 26 18:02:20 BRST 2016
(define (problem pb4)
	(:domain drinkanddrive-constraints-generated)
	(:requirements :strips :typing :negative-preconditions)
	(:objects
		loc1 loc2 loc3 loc4 loc5 loc6 loc7 loc8 loc9 - location
		bar2 bar3 bar5 - bar
	)
	(:init
		(at loc1)

		(connected loc6 loc3)
		(connected loc3 loc6)
		(connected loc3 loc1)
		(connected loc1 loc3)
		(connected loc1 loc5)
		(connected loc5 loc1)
		(connected loc5 loc2)
		(connected loc2 loc5)
		(connected loc2 loc9)
		(connected loc9 loc2)
		(connected loc3 loc8)
		(connected loc8 loc3)
		(connected loc3 loc4)
		(connected loc4 loc3)
		(connected loc4 loc7)
		(connected loc7 loc4)
		(connected loc4 loc8)
		(connected loc8 loc4)
		(connected loc5 loc3)
		(connected loc3 loc5)
		(connected loc6 loc5)
		(connected loc5 loc6)
		(connected loc9 loc6)
		(connected loc6 loc9)

		(in bar2 loc2)
		(in bar3 loc3)
		(in bar5 loc5)

	)

	(:goal
		(and
			(at loc9)
		)
	)
	(:constraints
		(and
			(preference a1 (sometime (drunk)))
		)
	)
)