; Generated by ProblemGenerator - Problem 5 at Sat Nov 26 18:02:20 BRST 2016
(define (problem pb5)
	(:domain drinkanddrive-constraints-generated)
	(:requirements :strips :typing :negative-preconditions)
	(:objects
		loc1 loc2 loc3 loc4 loc5 loc6 loc7 loc8 loc9 loc10 - location
		bar1 bar5 bar6 bar7 bar10 - bar
	)
	(:init
		(at loc1)

		(connected loc10 loc1)
		(connected loc1 loc10)
		(connected loc1 loc6)
		(connected loc6 loc1)
		(connected loc6 loc8)
		(connected loc8 loc6)
		(connected loc6 loc3)
		(connected loc3 loc6)
		(connected loc3 loc9)
		(connected loc9 loc3)
		(connected loc8 loc7)
		(connected loc7 loc8)
		(connected loc9 loc5)
		(connected loc5 loc9)
		(connected loc1 loc4)
		(connected loc4 loc1)
		(connected loc4 loc2)
		(connected loc2 loc4)
		(connected loc3 loc2)
		(connected loc2 loc3)
		(connected loc4 loc5)
		(connected loc5 loc4)
		(connected loc7 loc10)
		(connected loc10 loc7)
		(connected loc8 loc6)
		(connected loc6 loc8)

		(in bar1 loc1)
		(in bar5 loc5)
		(in bar6 loc6)
		(in bar7 loc7)
		(in bar10 loc10)

	)

	(:goal
		(and
			(at loc10)
		)
	)
	(:constraints
		(and
			(preference a1 (sometime (drunk)))
		)
	)
)