; Generated by ProblemGenerator - Problem 6 at Sat Nov 26 18:02:20 BRST 2016
(define (problem pb6)
	(:domain drinkanddrive-constraints-generated)
	(:requirements :strips :typing :negative-preconditions)
	(:objects
		loc1 loc2 loc3 loc4 loc5 loc6 loc7 loc8 loc9 loc10 loc11 - location
		bar2 bar7 bar8 - bar
	)
	(:init
		(at loc1)

		(connected loc6 loc10)
		(connected loc10 loc6)
		(connected loc10 loc5)
		(connected loc5 loc10)
		(connected loc6 loc9)
		(connected loc9 loc6)
		(connected loc9 loc1)
		(connected loc1 loc9)
		(connected loc6 loc2)
		(connected loc2 loc6)
		(connected loc10 loc8)
		(connected loc8 loc10)
		(connected loc2 loc11)
		(connected loc11 loc2)
		(connected loc1 loc3)
		(connected loc3 loc1)
		(connected loc3 loc7)
		(connected loc7 loc3)
		(connected loc1 loc4)
		(connected loc4 loc1)
		(connected loc2 loc6)
		(connected loc6 loc2)
		(connected loc4 loc6)
		(connected loc6 loc4)
		(connected loc4 loc9)
		(connected loc9 loc4)
		(connected loc5 loc10)
		(connected loc10 loc5)
		(connected loc6 loc8)
		(connected loc8 loc6)
		(connected loc7 loc9)
		(connected loc9 loc7)
		(connected loc11 loc9)
		(connected loc9 loc11)

		(in bar2 loc2)
		(in bar7 loc7)
		(in bar8 loc8)

	)

	(:goal
		(and
			(at loc11)
		)
	)
	(:constraints
		(and
			(preference a1 (sometime (drunk)))
		)
	)
)