; Generated by ProblemGenerator - Problem 7 at Sat Nov 26 18:02:20 BRST 2016
(define (problem pb7)
	(:domain drinkanddrive-constraints-generated)
	(:requirements :strips :typing :negative-preconditions)
	(:objects
		loc1 loc2 loc3 loc4 loc5 loc6 loc7 loc8 loc9 loc10 loc11 loc12 - location
		bar4 bar7 bar9 bar10 bar11 - bar
	)
	(:init
		(at loc1)

		(connected loc2 loc5)
		(connected loc5 loc2)
		(connected loc5 loc1)
		(connected loc1 loc5)
		(connected loc2 loc7)
		(connected loc7 loc2)
		(connected loc5 loc12)
		(connected loc12 loc5)
		(connected loc12 loc11)
		(connected loc11 loc12)
		(connected loc12 loc4)
		(connected loc4 loc12)
		(connected loc11 loc9)
		(connected loc9 loc11)
		(connected loc4 loc3)
		(connected loc3 loc4)
		(connected loc3 loc8)
		(connected loc8 loc3)
		(connected loc5 loc6)
		(connected loc6 loc5)
		(connected loc6 loc10)
		(connected loc10 loc6)
		(connected loc1 loc2)
		(connected loc2 loc1)
		(connected loc3 loc10)
		(connected loc10 loc3)
		(connected loc4 loc5)
		(connected loc5 loc4)
		(connected loc5 loc7)
		(connected loc7 loc5)
		(connected loc9 loc11)
		(connected loc11 loc9)
		(connected loc10 loc11)
		(connected loc11 loc10)
		(connected loc10 loc12)
		(connected loc12 loc10)
		(connected loc11 loc5)
		(connected loc5 loc11)

		(in bar4 loc4)
		(in bar7 loc7)
		(in bar9 loc9)
		(in bar10 loc10)
		(in bar11 loc11)

	)

	(:goal
		(and
			(at loc12)
		)
	)
	(:constraints
		(and
			(preference a1 (sometime (drunk)))
		)
	)
)